export const QUESTIONS_HAVE_ERROR = 'QUESTIONS_HAVE_ERROR';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const VOTE_ON_CHOICE = 'VOTE_ON_CHOICE';